# ===========================================================================
# NEON Bird Explorer — ui.R
# ===========================================================================
# v2 flow: the sidebar is GONE. The national picker map IS the way to select a
# site (tap a dot -> "Explore this site"); the relocated select panel below the
# map is the by-name fallback. The two controls that must stay reachable
# everywhere (theme toggle + "How it works") live in a slim top bar. The loaded
# view's hero band carries a "change site" link and a "report" download.
ui <- bslib::page_fillable(
  theme = app_theme, fillable = FALSE,
  window_title = "NEON Bird Explorer",
  tags$head(
    tags$link(rel = "preconnect", href = "https://fonts.googleapis.com"),
    tags$link(rel = "preconnect", href = "https://fonts.gstatic.com", crossorigin = NA),
    tags$link(rel = "stylesheet", href = "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700&family=Rubik:wght@400;500;600;700;800&display=swap"),
    tags$link(rel = "stylesheet", href = "https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.min.css"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.all.min.js"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/canvas-confetti@1.9.2/dist/confetti.browser.min.js"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/html-to-image@1.11.13/dist/html-to-image.js"),
    tags$link(rel = "stylesheet", href = asset_url("styles.css")),
    tags$link(rel = "stylesheet", href = asset_url("bird.css")),
    tags$script(src = asset_url("app.js")),
    tags$script(src = asset_url("pincards.js"))
  ),
  useShinyjs(),

  # ---- persistent top control bar (theme + help) -------------------------
  # Replaces the sidebar's always-on controls. Stays top-right above the hero.
  div(class = "top-bar",
    div(class = "top-bar-brand",
      tags$span(class = "tb-mark", "\U0001F426"),
      tags$span(class = "tb-title", "Bird Explorer")),
    div(class = "top-bar-actions",
      div(class = "tb-temp",
        tags$span(class = "tb-temp-lab", bs_icon("thermometer-half")),
        radioButtons("tempUnit", NULL, choices = c("°F" = "F", "°C" = "C"), selected = "F", inline = TRUE)),
      actionButton("help", tagList(bs_icon("question-circle"), " How it works"),
                   class = "btn-outline-dark btn-sm tb-help"),
      div(class = "tb-theme",
        tags$span(class = "tb-theme-lab", bs_icon("circle-half")),
        input_dark_mode(id = "colorMode", mode = "light")))
  ),

  div(id = "loadOverlay", class = "load-overlay", div(class = "load-card",
    div(class = "load-spin mascot-spin", MASCOT_CRITTER), div(class = "load-title", "Loading site data"),
    div(id = "loadSite", class = "load-site"), div(class = "load-bar"),
    div(class = "load-note", "Building the species board, detection profiles, and maps."))),

  uiOutput("heroStats"),

  # "Open a species profile" picker — was in the sidebar, now a hidden body block
  # revealed on site load (server: shinyjs::show("spPickerWrap")). Same ids
  # (spSel, surpriseBtn) so the server logic is untouched.
  hidden(div(id = "spPickerWrap", class = "sp-picker-wrap",
    div(class = "spw-row",
      div(class = "spw-sel",
        selectizeInput("spSel", label = tagList(bs_icon("search"), " Open a species profile"), choices = NULL,
                       width = "100%", options = list(placeholder = "Pick a species…"))),
      actionButton("surpriseBtn", tagList(bs_icon("dice-5-fill"), " Surprise me"),
                   class = "btn-outline-dark spw-surprise")))),

  div(id = "splash",
    div(class = "splash-guide",
      div(class = "sg-bubble", "Pick a site to start"),
      div(class = "sg-mascot", MASCOT_CRITTER)),
    div(class = "splash",
    div(class = "app-hero app-hero-splash",
      h1(class = "app-title", "NEON Bird Explorer", span(class = "title-tag", "unofficial")),
      p(class = "app-subtitle", "Who's singing where. Every bird species NEON counts, how widespread and how often heard, the distance at which each is detected, and how whole communities shift across a continent of climates. Built on 6-minute breeding-season point counts (DP1.10003.001).")),
    p(tags$b("Tap a site on the map"), " (sized by richness, coloured by biome) to explore it, or pick one by name in the panel below. ", tags$b("46 sites"), " from arctic tundra to Caribbean dry forest."),
    div(class = "picker-map-wrap", leafletOutput("nationalPicker", height = "440px")),

    # ---- relocated select panel (was the sidebar) ----------------------
    # Same input ids the server's cascade + load path depend on (stateSel,
    # site, loadBtn). Tapping a dot is the primary path; this panel is the
    # by-name fallback. Same ids, so server.R is untouched.
    div(class = "select-panel",
      div(class = "sp-head", bs_icon("sliders"), " Or pick a site by name"),
      div(class = "sp-row",
        div(class = "sp-field",
          selectInput("stateSel", label = tagList(bs_icon("geo-alt-fill"), " State"), choices = NULL, width = "100%")),
        div(class = "sp-field",
          selectInput("site", label = tagList(bs_icon("pin-map-fill"), " Site"), choices = NULL, width = "100%"))),
      uiOutput("siteBio"),
      actionButton("loadBtn", tagList(bs_icon("globe-americas"), " Explore this site"),
                   class = "btn-primary btn-lg w-100 load-btn sp-load", onclick = "smtLoadStart()")),

    tags$details(class = "site-browse",
      tags$summary(class = "site-browse-summary",
        tags$span(class = "sbs-label", bs_icon("list-ul"), " Browse all 46 sites as a list"),
        tags$span(class = "sbs-chevron", bs_icon("chevron-down"))),
      div(class = "site-browse-body", uiOutput("siteCards"))))),
  div(id = "mainTabsWrap", class = "main-tabs-wrap",
    div(class = "hero-caveat", bs_icon("soundwave"),
      tags$span(HTML("Counts are a <b>detection index</b> (birds per 6-minute point-count), not a population. A loud species and a quiet one at equal density give unequal counts."))),
    navset_card_tab(id = "tabs",
      nav_panel(title = tagList(bs_icon("compass"), " Overview"), value = "overview",
        div(class = "home-nav",
          actionButton("goCommunity", tagList(bs_icon("diagram-3-fill"), div("Community"), tags$small("richness & how many")), class = "home-btn"),
          actionButton("goBoard", tagList(bs_icon("bullseye"), div("Bird Board"), tags$small("every species, pinnable")), class = "home-btn home-btn-star"),
          actionButton("goClimate", tagList(bs_icon("globe-americas"), div("Across the continent"), tags$small("46 sites by climate")), class = "home-btn"),
          actionButton("goSpecies", tagList(bs_icon("feather"), div("Species Profile"), tags$small("one species up close")), class = "home-btn"),
          actionButton("goMap", tagList(bs_icon("map-fill"), div("Map"), tags$small("grids across the site")), class = "home-btn")),
        card(full_screen = TRUE,
          card_head("bar-chart-steps", "Most-detected species",
            info_pop("Detection index",
              p("Each species' ", tags$b("detection index"), ", birds counted per point-count, coloured by how it was first detected (", tags$span(style="color:#1a8a5a;font-weight:700","● singing"), " / ", tags$span(style="color:#3a8fd6;font-weight:700","▲ calling"), " / ", tags$span(style="color:#D55E00;font-weight:700","■ visual"), "). Each method also carries a marker shape, so it reads without relying on colour."),
              p(class="caveat", bs_icon("exclamation-triangle"), " This is a ", tags$b("detection index, not a population"), ": a loud species and a quiet one at equal density give unequal counts. NEON records distance + timing so detectability can be modelled (see a species' detection-decay)."))),
          uiOutput("overviewInsight"),
          spin(plotlyOutput("topBar", height = "440px"))),
        card(card_head("stars", "The story so far", info_pop("Story", p("Written from this site's live data."))),
          uiOutput("siteInsights")),
        card(full_screen = TRUE,
          card_head("calendar-range", "When the counts happen, the breeding window in the site's year",
            info_pop("Seasonal context",
              p("The shaded band is when NEON ran its breeding point counts here; the curves are the site's ", tags$b("average green-up and temperature by month"), " (co-located NEON plant-phenology + air-temperature data, ", tags$em("not"), " a bird measurement)."),
              p("It shows ", tags$b("when"), " counts happen against the seasonal cycle, context, not a bird-vs-environment driver model. Counts run only once or twice a year, so there's no within-season bird trend to track."))),
          uiOutput("seasonInsight"),
          spin(plotlyOutput("seasonStrip", height = "260px")))),
      nav_panel(title = tagList(bs_icon("diagram-3-fill"), " Community"), value = "community",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("How many birds live here?"),
          p("Species richness, a bias-corrected estimate of how many species use the site, and whether enough points were counted to know."),
          span(class = "scope-chip scope-site", bs_icon("geo-alt-fill"), " Showing this site only"))),
        layout_columns(col_widths = c(7, 5),
          card(full_screen = TRUE,
            card_head("graph-up", "Species accumulation (by point-counts)",
              info_pop("Accumulation", p("As more point-counts (each point × year is one count) accumulate, how many species turn up. A flattening curve means most detectable species have been found."))),
            uiOutput("accumInsight"), spin(plotlyOutput("accumPlot", height = "340px"))),
          card(full_screen = TRUE,
            card_head("calculator", "How many species really? (Chao2)",
              info_pop("Chao2", p(tags$b("Chao2"), " is an incidence-based, bias-corrected ", tags$b("minimum"), " estimate of richness. Point counts miss secretive, nocturnal, and rare species, so the true total is higher than the observed."))),
            uiOutput("chaoBanner")))),
      nav_panel(title = tagList(bs_icon("bullseye"), " Bird Board"), value = "board",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Every species on one board",
             info_pop("Bird Board",
               p("Each dot is a ", tags$b("species"), ", placed by ", tags$b("ubiquity"), " (% of points where it's ever detected, a less count-biased axis than the index, though still a detection floor) and its ", tags$b("detection index"), " (birds per point-count)."),
               p(tags$b("Tap a dot"), " to pin its card; tap “Open species profile” for its full detection profile. Faint dots are too few detections to place reliably."))),
          p("Each dot is a species, how widespread × how often counted. Tap to pin a card; open any species' full profile."),
          span(class = "scope-chip scope-site", bs_icon("geo-alt-fill"), " Showing this site only")),
          div(class = "sizelab-controls",
            selectInput("boardColor", tagList(bs_icon("palette"), " Colour by"),
                        choices = c("Detection method" = "method"), selected = "method", width = "200px"))),
        card(full_screen = TRUE,
          card_head("bullseye", "Ubiquity × detection index, by species",
            info_pop("Reading this", p("Top-right = everyone's neighbour (widespread + often counted); top-left = locally abundant specialist; bottom-right = thinly everywhere. The ", tags$span(style="color:#9a6b0f;font-weight:700","gold diamond"), " is the species you're viewing."),
              p("Dots are coloured AND shaped by first-detection method, so it reads without relying on colour: ", tags$span(style="color:#1a8a5a;font-weight:700","● singing"), " / ", tags$span(style="color:#3a8fd6;font-weight:700","▲ calling"), " / ", tags$span(style="color:#D55E00;font-weight:700","■ visual"), " / ", tags$span(style="color:#7a4a2a;font-weight:700","◆ drumming"), "."))),
          div(class = "sizelab-toolbar",
            tags$button(class = "smt-snap-btn", type = "button", onclick = "smtSaveScatter()", bsicons::bs_icon("camera-fill"), " Download (with pinned cards)"),
            downloadButton("boardCsv", "Download table (CSV)", class = "smt-clear-btn"),
            tags$button(class = "smt-clear-btn", type = "button", onclick = "smtClearPins()", bsicons::bs_icon("eraser-fill"), " Clear pins"),
            tags$span(class = "sizelab-hint", bs_icon("hand-index-thumb"), " interactive · tap a dot to pin its card")),
          div(class = "smt-pinnable", id = "boardPin", spin(plotlyOutput("birdBoard", height = "540px")))),
        uiOutput("spCardSlot")),
      nav_panel(title = tagList(bs_icon("globe-americas"), " Across the continent"), value = "climate",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("One protocol, 46 sites, a continent of climates"),
          p("Each dot is a NEON site, placed by its breeding-season climate against its bird community. Tap a dot to pin its card or jump to that site."),
          span(class = "scope-chip scope-all", bs_icon("globe-americas"), " All 46 NEON sites, not just this one")),
          div(class = "sizelab-controls",
            selectInput("gradMetric", tagList(bs_icon("bar-chart"), " Community metric (y)"),
              choices = c("Richness · effort-rarefied" = "rarefied", "Richness · observed (raw)" = "observed",
                          "Common-species diversity (Hill q1)" = "hill1", "Mean ubiquity" = "ubiquity",
                          "Singing share (% of detections)" = "singing",
                          "Birds per count (detection index)" = "index"), selected = "rarefied", width = "240px"),
            radioButtons("gradX", "Climate axis (x)", inline = TRUE,
              choices = c("Temperature · 46 sites" = "temp", "Precipitation · 19 sites" = "precip"), selected = "temp"))),
        card(full_screen = TRUE,
          card_head("globe-americas", "Bird community across the climate gradient",
            info_pop("Reading this",
              p("Warmer, more-productive sites tend to hold more breeding-bird species, a continental ", tags$b("temperature–productivity gradient"), ". Each dot is a site; ", tags$b("size = survey effort"), " (points counted); colour = biome; the ", tags$span(style="color:#9a6b0f;font-weight:700","gold diamond"), " is the site you're viewing."),
              p("By default, richness is ", tags$b("rarefied to a common number of point-counts"), " so it reflects the community, not how hard the site was surveyed (switch the metric with the selector to observed richness, Hill diversity, or mean ubiquity). This is ", tags$b("space-for-time"), ", 46 different places observed at once, not one site warming, so it's correlational, confounded by biome and latitude. Precipitation shows only the 19 sites with a NEON gauge."))),
          div(class = "sizelab-toolbar",
            tags$button(class = "smt-snap-btn", type = "button", onclick = "smtSaveClimate()", bsicons::bs_icon("camera-fill"), " Download (with pinned cards)"),
            downloadButton("gradientCsv", "Download table (CSV)", class = "smt-clear-btn"),
            tags$button(class = "smt-clear-btn", type = "button", onclick = "smtClearPins()", bsicons::bs_icon("eraser-fill"), " Clear pins"),
            tags$span(class = "sizelab-hint", bs_icon("hand-index-thumb"), " interactive · tap a site to pin its card")),
          div(class = "smt-pinnable", id = "climatePin", spin(plotlyOutput("climateGradient", height = "560px"))))),
      nav_panel(title = tagList(bs_icon("search"), " Search"), value = "search",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Search the network"),
          p("Look across all 46 NEON sites at once, no loading or fetching. Find every site where a species was detected, or list the sites that pass a threshold. Pick a result to load that site and open its Overview."),
          span(class = "scope-chip scope-all", bs_icon("globe-americas"), " All 46 NEON sites"))),
        radioButtons("searchMode", NULL, inline = TRUE,
          choices = c("Find a species" = "taxon", "Threshold query" = "threshold"),
          selected = "taxon"),
        # (a) FIND A SPECIES
        conditionalPanel("input.searchMode == 'taxon'",
          card(card_head("feather", "Find a species across the network"),
            div(class = "search-controls",
              selectizeInput("searchSp", "Species (common or scientific name)",
                choices = NULL, width = "420px",
                options = list(placeholder = "Start typing a bird name…",
                               maxOptions = 1200)))),
          card(card_head("geo-alt-fill", "Sites where it was detected"),
            div(class = "search-cap", uiOutput("searchSpCaption")),
            div(style = "width:100%;", DTOutput("searchSpTable")))),
        # (b) THRESHOLD QUERY
        conditionalPanel("input.searchMode == 'threshold'",
          card(card_head("sliders", "Threshold query"),
            div(class = "search-controls",
              selectInput("threshKind", "Query", width = "300px",
                choices = c("Species detected at more than N sites" = "wide",
                            "Site richness above X species" = "rich")),
              conditionalPanel("input.threshKind == 'wide'",
                sliderInput("threshN", "More than this many sites", min = 1, max = 45, value = 20, step = 1, width = "320px")),
              conditionalPanel("input.threshKind == 'rich'",
                sliderInput("threshX", "More than this many species (per-site richness)", min = 0, max = 200, value = 100, step = 5, width = "320px")))),
          card(card_head("list-ul", "Matches"),
            div(class = "search-cap", uiOutput("searchThreshCaption")),
            div(style = "width:100%;", DTOutput("searchThreshTable"))))),
      nav_panel(title = tagList(bs_icon("feather"), " Species Profile"), value = "species", uiOutput("speciesProfile")),
      nav_panel(title = tagList(bs_icon("map-fill"), " Map"), value = "map",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Bird grids across the site"),
          p("Each marker is a NEON point-count grid, sized by richness and coloured by your chosen metric. ", tags$b("Tap a grid"), " for the full list of birds detected there."),
          span(class = "scope-chip scope-site", bs_icon("geo-alt-fill"), " Showing this site only")),
          div(class = "map-controls",
            selectInput("mapMetric", "Colour by", width = "180px", choices = c("Species richness" = "richness", "Birds per count" = "per_visit")),
            selectInput("view", "Basemap", width = "160px", choices = c("Terrain" = "Esri.WorldTopoMap", "Light" = "CartoDB.Positron", "Satellite" = "Esri.WorldImagery")))),
        spin(leafletOutput("map", height = "560px")),
        uiOutput("gridPanel")),
      nav_panel(title = tagList(bs_icon("info-circle"), " About"), value = "about", uiOutput("aboutPanel"))
    )),
  div(class = "ddl-footer",
    div(tags$a(class = "custom-cta", href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Bird%20Explorer",
      span(class = "hand", "\U0001F44B"), "Questions or feedback? Get in touch with Desert Data Labs.")),
    p(style = "margin-top:12px", HTML("Built by <strong>Desert Data Labs</strong> · Tucson, AZ · get in touch →"),
      tags$a(href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Bird%20Explorer", "desertdatalabs@gmail.com")),
    p(style = "font-size:12px;opacity:.85", "Data: NEON Breeding Landbird Point Counts (DP1.10003.001). Not affiliated with NEON, Battelle, or the NSF. An educational data-exploration tool."))
)
